# Pipeline Inicial
name: CD Fake
on: 
    workflow_dispatch: qweqe
jobs:
    deploy-fake:
        environment: homologacao
        runs-on: ubuntu-latest
        steps:
            - name: Fake de deploy em ambiente
              run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
              

